obj-$(CONFIG_OPPO_COMMON_SOFT)	+=  oppo_project/
obj-$(CONFIG_OPPO_DEVICE_IFNO)	+=  oppo_devinfo/
obj-$(CONFIG_OPPO_DEBUG_ASSERT)	+=  oppo_trace/
obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/
#ifdef VENDOR_EDIT
#//John.Xu@PhoneSw.AudioDriver, 2016/02/22, Add for critical_log
obj-y     +=  oppo_criticallog/
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
obj-$(CONFIG_OPPO_HYPNUS)     +=  oppo_hypnus/
#endif /* VENDOR_EDIT */
